# Generated by Django 4.1.6 on 2023-02-09 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Facultad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombreF",
                    models.CharField(
                        max_length=100, verbose_name="Nombre de la Facultad"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Persona",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombres",
                    models.CharField(max_length=100, verbose_name="Nombres Completos"),
                ),
                (
                    "apellidos",
                    models.CharField(
                        max_length=100, verbose_name="Apellidos Completos"
                    ),
                ),
                ("cedula", models.CharField(max_length=10, verbose_name="Cedula")),
                (
                    "celular",
                    models.CharField(max_length=10, verbose_name="Nro celular"),
                ),
                (
                    "nacionalidad",
                    models.CharField(max_length=100, verbose_name="Nacionalidad"),
                ),
                (
                    "correo",
                    models.EmailField(
                        max_length=100, verbose_name="Correo electronico"
                    ),
                ),
                ("edad", models.IntegerField(verbose_name="Edad")),
            ],
        ),
        migrations.CreateModel(
            name="Rol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text="Ingrese el nombre del rol",
                        max_length=80,
                        verbose_name="Ingresar el nombre del rol",
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(
                        help_text="Descripcion del rol",
                        verbose_name="Ingrese una descrición detallada del rol",
                    ),
                ),
            ],
            options={
                "verbose_name": "Permiso del sistema",
                "verbose_name_plural": "Permisos para usuarios",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="TipoTramite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombrett",
                    models.CharField(max_length=100, verbose_name="Tipo de tramite"),
                ),
                (
                    "descripcion",
                    models.TextField(verbose_name="Que contempla este tramite"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tramite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombreT",
                    models.CharField(max_length=100, verbose_name="Nombre del tramite"),
                ),
                (
                    "descripcion",
                    models.TextField(verbose_name="Para quienes va dirigido"),
                ),
                (
                    "tiempoestimado",
                    models.IntegerField(verbose_name="Tiempo que demora el tramite"),
                ),
                (
                    "necesidad",
                    models.TextField(
                        verbose_name="Que necesita para solicitar este tramite"
                    ),
                ),
                ("costo", models.FloatField()),
                (
                    "tipoTramite",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="administrativo.tipotramite",
                        verbose_name="Tipo de Tramite",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PedidoTramite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tramite",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="administrativo.tramite",
                        verbose_name="Tramite",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Carrera",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombreC",
                    models.CharField(
                        max_length=200, verbose_name="Nombre de la carrera"
                    ),
                ),
                (
                    "facultad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="administrativo.facultad",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tramitante",
            fields=[
                (
                    "persona_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="administrativo.persona",
                    ),
                ),
                (
                    "carrera",
                    models.ManyToManyField(
                        to="administrativo.carrera", verbose_name="Carrera"
                    ),
                ),
            ],
            bases=("administrativo.persona",),
        ),
    ]
